### ISSUE TITLE
Kafka message bus losing offsets and replaying intermediate stream messages

### ISSUE THREAD

**Issue by clemper** [spring-projects/spring-xd#1727]
Hi,

When we restart our entire Spring XD stack we sometimes see messages from the intermediate kafka topics in the message bus get replayed.  As far as we can tell, the message bus can't determine the offset for the intermediate kafka topic and so starts over at the smallest offset.  

Our kafka message bus config looks like:

```YAML
    kafka:
      brokers:                                 localhost:9092
      zkAddress:                               localhost:2181
      mode:                                    embeddedHeaders
      headers:                                 domain
      socketBufferSize:                        2097152
      offsetStoreTopic:                        SpringXdOffsets
      offsetStoreSegmentSize:                  25000000
      offsetStoreRetentionTime:                60000
      offsetStoreRequiredAcks:                 1
      offsetStoreMaxFetchSize:                 1048576
      offsetStoreBatchBytes:                   16384
      offsetStoreBatchEnabled:                 false
      offsetStoreBatchTime:                    1000
      offsetUpdateTimeWindow:                  10000
      offsetUpdateCount:                       0
      offsetUpdateShutdownTimeout:             2000
      default:
        batchSize:                 16384
        batchTimeout:              0
        replicationFactor:         1
        concurrency:               1
        requiredAcks:              1
        compressionCodec:          none
        autoCommitEnabled:         true
        queueSize:                 1 # must be a power of 2
        fetchSize:                 1048576
        minPartitionCount:         5
```

I am just looking for any hints that might help us figure out what is happening.  Thanks for your help.  

Chris
